server:
  port: 8077
  servlet:
    context-path: /quesBank
  max-http-header-size: 102400

mybatis-plus:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.physics.quesbank.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
   application:
      name: authCenter
   profiles:
     include: constants
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.92.248.124:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: tian1qaz!QAZ
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true

   devtools:
      restart:
         enabled: true
         additional-paths: src/main/java

imageUpload:
#   path: /usr/local/quesBank/img/
   path: D:/img/

htmlToPdf:
   htmlTemplate: <!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>试题</title><style>body,html{height:100%;width:100%;margin:0;}.recordContainerShowQuestion{width:100%;min-height:150px;margin-left:auto;margin-right:auto;line-height:25px;float:none;height:auto;cursor:default;padding-left:20px;border-radius:5px;}.contentShowQuestion{width:100%;height:auto;min-height:150px;}.showDemoShowQuestion{overflow:hidden;}.container{height:100%;width:100%;}.container * {box-sizing:border-box;height:100%;}[class *= 'col-']{float:left;min-height:1px;padding:0px;}.col-sm-25{width:0%;}.col-sm-50{width:100%;}img{vertical-align:middle;}p{margin:0}</style></head><body><div class="container"><div class="col-sm-25"></div><div class="col-sm-50 ques">TEMPLATE</div><div class="col-sm-2"></div></div></body></html>
#   htmlPath: /usr/local/quesBank/
#   pdfPath: /usr/local/quesBank/
   htmlPath: D:/
   pdfPath: D:/